apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: visual-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: humza1535/visual-search-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_URI
              value: "mongodb://$(MONGO_USER):$(MONGO_PASS)@mongo:27017/"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: JWT_SECRET_KEY
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGO_DB_NAME
            - name: MONGO_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGO_COLLECTION_NAME
            - name: MONGO_USERS_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGO_USERS_COLLECTION_NAME
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT
