apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: visual-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: humza1535/visual-search-frontend:latest
          ports:
            - containerPort: 80
