apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: visual-search
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW5wYXNz
  JWT_SECRET_KEY: ZGV2LXNlY3JldC1rZXktY2hhbmdlLW1l
